### ISSUE TITLE
Stability Investigation

### ISSUE THREAD

**Issue by thala321** [massbitprotocol/massbitprotocol#168]
**Todo:**
- [x] Index Manager logs by day 
- [x] Start chain-reader with log 
- [x] After two days, investigate if the error still happens ?

---
**Some info:** 
The day we start our indexers : index-manager-2021-08-16T09:17:57.log
With this commit (3009c23f0a62379f9034e3fed3f1a46fed16418a), the Solana Indexers stop after 2-3 days. (Substrate is still running 'till 23-8-2021) 
- The size of total DB is: 234 GB
- The size of Solana Transaction Ts Table is: 75 GB
- The size of Solana Log Message Ts table is: 124 GB 
```
massbit@VuAtCodelight:~/work/massbitprotocol$ git show
commit 3009c23f0a62379f9034e3fed3f1a46fed16418a (HEAD -> main, tag: v0.4, origin/main, origin/HEAD)
```
- The problem maybe because of:
  -  chain reader stopped ?
  -  the Solana Indexer thread stopped ?
  -  Solana Proxy stopped ?
  -  Out of memory ?
  -  Out of storage ?
  ```
  massbit@VuAtCodelight:~/work/massbitprotocol/log$ df -h .
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/sda2       938G  506G  385G  57% /
```

**Comment by thala321** [comment]
@anhhuy0501 you can find more detail in this PR https://github.com/massbitprotocol/massbitprotocol/pull/171 . We should make a PR to fix the socket connection with Solana Chain Reader closed after running 3 days
