### ISSUE TITLE
Solana Explorer - Improve chain-reader/Indexer

### ISSUE THREAD

**Issue by vuviettai** [massbitprotocol/massbitprotocol#307]
# Problem
Currently, the indexing speed and chain-reader consuming block data is out of sync and will die after a while

# Todo
- [x] Remove decode for general data indexer (2 days) @vuviettai 
- [x] Filter relevant transactions (2 days) @anhhuy0501  
- [x] Batch RPC call (1 day) @anhhuy0501
